---
title: "Data Sets"
author: 'STA321: Week #3 Note'
date: "2/3/2021"
output:
  html_document:
    toc: yes
    toc_depth: 4
    fig_width: 6
    fig_height: 4
    fig_caption: yes
    number_sections: yes
    theme: readable
  pdf_document: 
    toc: yes
    toc_depth: 4
    fig_caption: yes
    number_sections: yes
  word_document:
    toc: yes
    toc_depth: '4'
---

<style type="text/css">
h1.title {
  font-size: 20px;
  color: DarkRed;
  text-align: center;
}
h4.author { /* Header 4 - and the author and data headers use this too  */
    font-size: 18px;
  font-family: "Times New Roman", Times, serif;
  color: DarkRed;
  text-align: center;
}
h4.date { /* Header 4 - and the author and data headers use this too  */
  font-size: 18px;
  font-family: "Times New Roman", Times, serif;
  color: DarkBlue;
  text-align: center;
}
h1 { /* Header 3 - and the author and data headers use this too  */
    font-size: 22px;
    font-family: "Times New Roman", Times, serif;
    color: darkred;
    text-align: center;
}
h2 { /* Header 3 - and the author and data headers use this too  */
    font-size: 18px;
    font-family: "Times New Roman", Times, serif;
    color: navy;
    text-align: left;
}

h3 { /* Header 3 - and the author and data headers use this too  */
    font-size: 15px;
    font-family: "Times New Roman", Times, serif;
    color: navy;
    text-align: left;
}

h4 { /* Header 4 - and the author and data headers use this too  */
    font-size: 18px;
    font-family: "Times New Roman", Times, serif;
    color: darkred;
    text-align: left;
}
</style>



```{r setup, include=FALSE}
# code chunk specifies whether the R code, warnings, and output 
# will be included in the output files.
library(knitr)
library(lessR) 
knitr::opts_chunk$set(echo = TRUE,           # include code chunk in the output file
                      warnings = FALSE,       # sometimes, you code may produce warning messages,
                                              # you can choose to include the warning messages in
                                              # the output file. 
                      results = TRUE          # you can also decide whether to include the output
                                              # in the output file.
                      )   
```


## Binary Classification
* [Indian Liver Patient Records](https://www.kaggle.com/uciml/indian-liver-patient-records)
* [Synthetic Financial Data for Fraud Detection](https://www.kaggle.com/ntnu-testimon/paysim1)
* [Business and Industry Reports](https://www.kaggle.com/census/business-and-industry-reports)
* [Can You Predict Product Backorders?](https://www.kaggle.com/tiredgeek/predict-bo-trial)
* [Exoplanet Hunting in Deep Space](https://www.kaggle.com/keplersmachines/kepler-labelled-time-series-data)
* [Adult Census Income](https://www.kaggle.com/uciml/adult-census-income)

## Multiclass Classification
* [Iris Species](https://www.kaggle.com/uciml/iris)
* [Fall Detection Data from China](https://www.kaggle.com/pitasr/falldata)
* [Biomechanical Features of Orthopedic Patients](https://www.kaggle.com/uciml/biomechanical-features-of-orthopedic-patients)

## Regression
* [Video Game Sales with Ratings](https://www.kaggle.com/rush4ratio/video-game-sales-with-ratings)
* [NYC Property Sales](https://www.kaggle.com/new-york-city/nyc-property-sales)
* [Gas Sensor Array Under Dynamic Gas Mixtures](https://www.kaggle.com/uciml/gas-sensor-array-under-dynamic-gas-mixtures)


