---
title: "Some General Comments on Writing Statistics Reports"
author: 'Cheng Peng'
date: "West Chester University"
output:
  html_document: 
    toc: yes
    toc_float: true
    toc_depth: 4
    fig_width: 6
    fig_height: 4
    fig_caption: yes
    number_sections: yes
    theme: readable
  word_document: 
    toc: yes
    toc_depth: 4
    fig_caption: yes
    keep_md: yes
  pdf_document:
    toc: yes
    toc_depth: 4
    fig_caption: yes
    number_sections: yes
    fig_width: 5
    fig_height: 4
---
<style type="text/css">

div#TOC li {
    list-style:none;
    background-image:none;
    background-repeat:none;
    background-position:0;
}
h1.title {
  font-size: 24px;
  color: DarkRed;
  text-align: center;
}
h4.author { /* Header 4 - and the author and data headers use this too  */
    font-size: 18px;
  font-family: "Times New Roman", Times, serif;
  color: DarkRed;
  text-align: center;
}
h4.date { /* Header 4 - and the author and data headers use this too  */
  font-size: 18px;
  font-family: "Times New Roman", Times, serif;
  color: DarkBlue;
  text-align: center;
}

h1 { /* Header 3 - and the author and data headers use this too  */
    font-size: 20px;
    font-family: "Times New Roman", Times, serif;
    color: darkred;
    text-align: center;
}
h2 { /* Header 3 - and the author and data headers use this too  */
    font-size: 18px;
    font-family: "Times New Roman", Times, serif;
    color: navy;
    text-align: left;
}

h3 { /* Header 3 - and the author and data headers use this too  */
    font-size: 16px;
    font-family: "Times New Roman", Times, serif;
    color: navy;
    text-align: left;
}

</style>



```{r setup, include=FALSE}
# code chunk specifies whether the R code, warnings, and output 
# will be included in the output files.
if (!require("knitr")) {
   install.packages("knitr")
   library(knitr)
}

knitr::opts_chunk$set(echo = TRUE,       
                      warnings = FALSE,   
                      results = TRUE,   
                      message = FALSE,
                      fig.align='center', 
                      fig.pos = 'ht')
#knitr::opts_knit$set(root.dir = 'C:\\STA551\\wkdir0')
```



# Introduction

This short note outlines some specifics everyone should incorporated in the reports.

Although heading and titles are similar, they are distinct: A title leads the entire document and captures its content in one or two phrases; a heading leads only a chapter or section and captures only the content of that chapter or section. 

# About the Title

The title needs to be simple and direct
It should be informative
It should be specific, accurate, and functional (with essential scientific “keywords” for indexing)
It should be concise, precise, and should include the main theme of the paper
It should not be misleading or misrepresentative
It should not be too long or too short (or cryptic)
It should avoid whimsical or amusing words
It should avoid nonstandard abbreviations and unnecessary acronyms (or technical jargon)
Important terms/keywords should be placed in the beginning of the title
Descriptive/neutral titles are preferred to declarative or interrogative titles

## Headings

The “title” should be 
* descriptive, 
* direct 
* accurate 
* appropriate 
* concise 
* precise 
* unique and 
* should **not** be misleading. 


# Section Heading


## Heading Length

Headings should be as long as it takes to clearly communicate the content of the sections they head. However, each heading should be as concise as possible – a good rule of thumb is to limit the heading length to one line.

## Higher-level vs. lower-level headings

Higher-level headings often make do with a single word (e.g. “Introduction” or “Methods”), while
lower-level headings are often longer. This is because higher-level headings cover more general content and provide an overview. One word is clear enough because everyone already knows what happens in an introduction chapter – nothing more needs to be said.

Lower-level headings should use more specific terminology to help clarify the content of the section. These headings help readers find the exact information they’re looking for.


## Using descriptive headings
The main goal of a heading is to inform the reader of what content they can find in that section, so make your headings as descriptive as possible. The examples below show one non-descriptive heading and three descriptive headings that provide the reader with much more information.

GPS
Profile of GPS technology
Function of GPS in aviation
GPS before 1999

*Avoiding repetitive headings*: No two sections should focus on the exact same content, so no two headings should be identical. Instead of closing a chapter with “Summary,” for example, try making the heading little more descriptive: “Summary of X.”

## Technical terms in headings

Documents in fields that rely heavily on jargon and technical language will contain headings that might not be clear to every reader. That’s fine as long as you keep your reader’s knowledge level in mind. However, if you don’t need the jargon to give a specific idea of your content, then avoid it.

## Capitalization, formatting and sequencing

At the outset, make a plan for how you will deal with matters of capitalization, formatting and sequencing of headings. Headings at the same level should be formatted the same. For instance, “Section 2.2” should get the same treatment as “Section 4.1”. They should also have parallel structure.



